### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by PedDavid** [PedDavid/NubDevEngineCpp#1]
- [ ] class naming convention
- [ ] Sounds: Manage multiple m_Handles
- [ ] KeyBoard getClicked (input Class)
- [ ] Program finish (delete window/context/audio)
- [x] BatchRenderer DrawString scaleX/scaleY
- [ ] Auto Scale Font
- [ ] redo "hack" in logging system for opengl calls (show file / line)
- [ ] glEnable(DEPTH_TEST) changes z disposition in 2d (layer/group) (elements added after are rendered first)
- [ ] colors inverted (ABGR)
